### ISSUE TITLE
Ошибка бл...

### ISSUE THREAD

**Issue by TheFaik** [Overwrite987/OvRandomTeleport#1]
Command exception: /rtp admin reload
org.bukkit.command.CommandException: Unhandled exception executing command 'rtp' in plugin OvRandomTeleport v1.3.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:28) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.commands.Commands.performCommand(Commands.java:357) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.commands.Commands.performCommand(Commands.java:347) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2251) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2225) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1562) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1540) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1533) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1491) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1498) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1345) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: duration cannot be negative: -1 SECONDS
        at com.github.benmanes.caffeine.cache.Caffeine.requireArgument(Caffeine.java:181) ~[caffeine-3.1.8.jar:3.1.8]
        at com.github.benmanes.caffeine.cache.Caffeine.expireAfterWrite(Caffeine.java:643) ~[caffeine-3.1.8.jar:3.1.8]
        at OvRandomTeleport.jar/ru.overwrite.rtp.utils.ExpiringMap.<init>(ExpiringMap.java:18) ~[OvRandomTeleport.jar:?]
        at OvRandomTeleport.jar/ru.overwrite.rtp.channels.Channel.<init>(Channel.java:177) ~[OvRandomTeleport.jar:?]
        at OvRandomTeleport.jar/ru.overwrite.rtp.RtpManager.setupChannels(RtpManager.java:156) ~[OvRandomTeleport.jar:?]
        at OvRandomTeleport.jar/ru.overwrite.rtp.RtpCommand.processAdminCommand(RtpCommand.java:115) ~[OvRandomTeleport.jar:?]
        at OvRandomTeleport.jar/ru.overwrite.rtp.RtpCommand.onCommand(RtpCommand.java:47) ~[OvRandomTeleport.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]

**Comment by TheFaik** [comment]
Прописываю команду /rtp admin reload и выходит вот это биба....

**Comment by TheFaik** [comment]
[02:01:06 ERROR]: Exception when TheFaikIi attempted to tab complete admin
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/rtp admin' in plugin OvRandomTeleport v1.3.0
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.Command.tabComplete(Command.java:91) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigSuggestionProvider.getSuggestions(BukkitCommandNode.java:112) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.2.9.jar:1.21-DEV-b2692f7]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:551) ~[leaf-1.21.jar:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:531) ~[leaf-1.21.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.sendServerSuggestions(ServerGamePacketListenerImpl.java:859) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions0$3(ServerGamePacketListenerImpl.java:820) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1562) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1540) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1533) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1491) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1498) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1345) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at OvRandomTeleport.jar/ru.overwrite.rtp.RtpCommand.onTabComplete(RtpCommand.java:191) ~[OvRandomTeleport.jar:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        ... 21 more

**Comment by Overwrite987** [comment]
> [02:01:06 ERROR]: Exception when TheFaikIi attempted to tab complete admin org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/rtp admin' in plugin OvRandomTeleport v1.3.0 at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?] at org.bukkit.command.Command.tabComplete(Command.java:91) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigSuggestionProvider.getSuggestions(BukkitCommandNode.java:112) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.2.9.jar:1.21-DEV-b2692f7] at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:551) ~[leaf-1.21.jar:?] at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:531) ~[leaf-1.21.jar:?] at net.minecraft.server.network.ServerGamePacketListenerImpl.sendServerSuggestions(ServerGamePacketListenerImpl.java:859) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions0$3(ServerGamePacketListenerImpl.java:820) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1562) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1540) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1533) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1491) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1498) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1345) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.jar:1.21-DEV-b2692f7] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 at OvRandomTeleport.jar/ru.overwrite.rtp.RtpCommand.onTabComplete(RtpCommand.java:191) ~[OvRandomTeleport.jar:?] at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?] ... 21 more

Эта ошибка была исправлена в дев билдах

**Comment by Overwrite987** [comment]
Теперь исправлена и первая

**Comment by TheFaik** [comment]
> Теперь исправлена и первая

Спасибо большое 🍺😅
