### ISSUE TITLE
Ошибка при выполнении команды перезагрузки.

### ISSUE THREAD

**Issue by TheFaik** [Overwrite987/OvRandomTeleport#3]
```
Command exception: /ovrandomteleport admin reload
org.bukkit.command.CommandException: Unhandled exception executing command 'ovrandomteleport' in plugin OvRandomTeleport v1.4.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:28) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:445) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:354) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:344) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:339) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2258) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2232) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1554) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1532) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1525) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1641) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.jar:1.21-DEV-9e75cdd]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.STATIONARY_WATER
        at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at org.bukkit.Material.valueOf(Material.java:130) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at OvRandomTeleport-1.4.2.jar/ru.overwrite.rtp.RtpManager.setupChannelAvoidance(RtpManager.java:191) ~[OvRandomTeleport-1.4.2.jar:?]
        at OvRandomTeleport-1.4.2.jar/ru.overwrite.rtp.RtpManager.setupChannels(RtpManager.java:79) ~[OvRandomTeleport-1.4.2.jar:?]
        at OvRandomTeleport-1.4.2.jar/ru.overwrite.rtp.RtpCommand.processAdminCommand(RtpCommand.java:115) ~[OvRandomTeleport-1.4.2.jar:?]
        at OvRandomTeleport-1.4.2.jar/ru.overwrite.rtp.RtpCommand.onCommand(RtpCommand.java:47) ~[OvRandomTeleport-1.4.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        ... 26 more
```

**Comment by TheFaik** [comment]
понял по ошибке, что он блоки не распознал
